openapi: "3.1.0"
info:
  title: "ConsultLogger API"
  description: "ConsultLogger API"
  version: "1.0.0"
servers:
  - url: "https://ConsultLogger"
paths:
  /specialties/topSpecialties:
    get:
      summary: "GET specialties/topSpecialties"
      operationId: "get"
      parameters:
        - name: "numOfUniquePatients"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "2"
      responses:
        "200":
          description: "OK"
          content:
            'application/json':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/TopSpecialtiesDTO"
        "500":
          description: "Bad Request"
components:
  schemas:
    TopSpecialtiesDTO:
      type: "object"
      properties:
        specialtyName:
          type: "string"
        numberOfPatients:
          type: "integer"
          format: "int64"